---

- name: Install Vault login script
  copy:
    src: ../files/scripts/vault/vaultlogin.sh
    dest: /usr/local/sbin/vaultlogin.sh
    owner: root
    group: root
    mode: 0770

- name: Install Vault client script
  copy:
    src: ../files/scripts/vault/getvaulttoken.sh
    dest: /usr/local/sbin/getvaulttoken.sh
    owner: root
    group: root
    mode: 0775

- name: create Vault secure introduction service
  copy:
    src: ../files/services/vault_secure_introduction.service
    dest: /etc/systemd/system/vault_secure_introduction.service
    owner: root
    group: root
    mode: 0664

- name: enable Vault SI service
  command: systemctl enable vault_secure_introduction.service